title: Quarkus guide
description: Guidelines for Rio Angular projets
repository: panchitoboy/quarkus-guide

remote_theme: rundocs/jekyll-rtd-theme

readme_index:
  with_frontmatter: true

exclude:
  - "Gemfile*"
  - "docker-compose.yml"
  - "vendor"

